const STORAGE_KEY='illuminate-dms-v1';
const SUPABASE_URL='https://kfeiwfvmvppepehywcgw.supabase.co';
const SUPABASE_KEY='sb_publishable_Ken7UfVMrwsPcevS5LUUvw_ne6XxZhw';
const VAPID_PUBLIC_KEY='BP5eFR1gG1Py7zG6CmT9Xa3F2M-8XUYJD1Zz0i0J41jEtgy5vGDTzoEsb82zD11SLibArAJv0f38kUa7tK93dP8';
const SESSION_KEY='illuminate-supabase-session';
const CLOUD_MODULES=['members','contributionTypes','payments','activities','schedules','rosters','designs'];
let cloudSession=null,cloudTimer=null,cloudWriteTimer=null,lastCloudUpdate='',authMode='signin',cloudReady=false;
const pages=[['dashboard','⌂','Dashboard'],['members','◎','Members & Skills'],['contributions','₦','Contributions'],['activities','◫','Activities'],['schedule','◷','Schedule & Roster'],['designs','◇','Designs'],['reports','▤','Reports']];
const seed={members:[{id:'m1',name:'Adaeze Okafor',phone:'0803 555 0182',email:'adaeze@example.org',birthday:'1994-08-14',status:'Active',role:'Team Lead',subunit:'Social Media',skills:'Canva:Advanced, Photography:Intermediate',functions:'Design, Coverage',trainings:'Brand storytelling',notes:''},{id:'m2',name:'Daniel Eze',phone:'0806 204 1129',email:'daniel@example.org',birthday:'1997-12-02',status:'Active',role:'Member',subunit:'Technical',skills:'Lighting:Advanced, Video:Intermediate',functions:'Lighting',trainings:'Safety training',notes:''},{id:'m3',name:'Grace Udo',phone:'0701 366 7712',email:'grace@example.org',birthday:'1995-07-28',status:'Active',role:'Coordinator',subunit:'Design',skills:'Canva:Advanced, Copywriting:Advanced',functions:'Design, Planning',trainings:'',notes:''},{id:'m4',name:'Samuel Obi',phone:'0812 777 4420',email:'samuel@example.org',birthday:'1992-10-09',status:'Inactive',role:'Member',subunit:'Photography',skills:'Photography:Advanced, Editing:Beginner',functions:'Coverage',trainings:'',notes:'On leave'}],contributionTypes:[{id:'c1',name:'Media Equipment Fund',amount:10000,due:'2026-08-31',status:'Active'},{id:'c2',name:'Q3 Welfare',amount:5000,due:'2026-09-15',status:'Active'}],payments:[{id:'p1',typeId:'c1',memberId:'m1',amount:10000,date:'2026-07-05'},{id:'p2',typeId:'c1',memberId:'m2',amount:6000,date:'2026-07-07'}],activities:[{id:'a1',title:'Lighting Masterclass',type:'Training',date:'2026-07-26',time:'10:00',venue:'Media Room',coordinator:'Daniel Eze',status:'Planned',notes:'Practical session'},{id:'a2',title:'Monthly Department Meeting',type:'Meeting',date:'2026-08-02',time:'16:00',venue:'Conference Hall',coordinator:'Grace Udo',status:'Planned',notes:''}],schedules:[{id:'s1',title:'July Strategy Meeting',date:'2026-07-27',time:'16:00',venue:'Media Room',coordinator:'Grace Udo',theme:'Excellence in service',notes:'Please arrive ten minutes early.',agenda:'16:00|16:10|Opening prayer|Opening and welcome|Adaeze Okafor|\n16:10|16:35|Department review|Review the month\'s work|Grace Udo|\n16:35|17:00|Planning|Upcoming celebrations|Samuel Obi|'}],rosters:[{id:'r1',event:'Sunday Celebration Service',date:'2026-07-26',venue:'Main Auditorium',coordinator:'Adaeze Okafor',notes:'All team members should check in at the media desk.',assignments:'Photography|Samuel Obi|Daniel Eze|07:00|07:30|Auditorium|Confirmed|\nSocial Media|Adaeze Okafor|Grace Udo|07:15|07:45|Media desk|Confirmed|'}],designs:[{id:'d1',title:'July Celebrants',category:'Birthday',date:'2026-07-25',person:'July celebrants',canva:'https://www.canva.com/',thumbnail:'',status:'Pending',notes:'Awaiting final approval'},{id:'d2',title:'Anniversary Feature',category:'Wedding Anniversary',date:'2026-08-04',person:'The Okafors',canva:'https://www.canva.com/',thumbnail:'',status:'Approved',notes:''}]};
let state=load();let current='dashboard';let editContext=null;let calendarDate=new Date();let activityTypeFilter='All';
function load(){try{let data={...structuredClone(seed),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')};data.members=data.members.map((m,i)=>({...m,subunit:['Finance','Admin','Technical','Member','Welfare'].includes(m.subunit)?m.subunit:'Member',skill:m.skill||['General schedule','Scripture Projection','using VMIX'][i%3],skillLevel:m.skillLevel||['Advanced','Intermediate','Beginner'][i%3]}));return data}catch{return structuredClone(seed)}}
function save(message='Changes saved'){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));document.getElementById('lastSaved').textContent=cloudSession?'Syncing…':'Saved offline';toast(message);render();queueCloudSync()}
function id(prefix){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,5)}
function esc(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v)||0)}
function dateFmt(v,opts={day:'numeric',month:'short',year:'numeric'}){if(!v)return '—';return new Date(v+'T00:00:00').toLocaleDateString('en-NG',opts)}
function initials(n=''){return n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
document.getElementById('nav').innerHTML=pages.map(([k,i,l])=>`<button class="nav-button" data-page="${k}"><span class="nav-icon">${i}</span>${l}</button>`).join('');
document.getElementById('nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b){current=b.dataset.page;closeMenu();render()}};
document.getElementById('menuButton').onclick=()=>{document.getElementById('sidebar').classList.add('open');document.getElementById('scrim').classList.add('show')};
document.getElementById('scrim').onclick=closeMenu;function closeMenu(){document.getElementById('sidebar').classList.remove('open');document.getElementById('scrim').classList.remove('show')}
document.getElementById('backupButton').onclick=backup;document.getElementById('restoreInput').onchange=restore;
function render(){document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.page===current));document.getElementById('pageTitle').textContent=current==='notifications'?'Notifications':pages.find(p=>p[0]===current)[2];document.getElementById('view').innerHTML=views[current]();bindView();updateNotificationBadge();postRenderEnhancements()}
const metrics=()=>{let active=state.members.filter(m=>m.status==='Active').length,inactive=state.members.length-active,pending=state.designs.filter(d=>designStatus(d)!=='Past').length,training=state.activities.filter(a=>a.type==='Training'&&a.status!=='Completed').length;return {active,inactive,pending,training}};
const views={
dashboard(){let m=metrics(),upcoming=[...state.members].map(x=>({...x,next:nextBirthday(x.birthday)})).sort((a,b)=>a.next-b.next).slice(0,4);return `<section class="hero"><div><p class="eyebrow">WELCOME BACK</p><h2>Serving with clarity and excellence.</h2><p>Your department at a glance — everything updates as your records change.</p></div><div class="hero-date"><strong>${new Date().toLocaleDateString('en-NG',{weekday:'long'})}</strong><span>${new Date().toLocaleDateString('en-NG',{day:'numeric',month:'long',year:'numeric'})}</span></div></section><section class="metrics">${metric('Total members',state.members.length,'Department directory')}${metric('Active members',m.active,'Currently serving')}${metric('Inactive',m.inactive,'Away or unavailable')}${metric('Contributions',state.contributionTypes.filter(x=>x.status==='Active').length,'Active collections')}${metric('Pending designs',m.pending,'Needs attention')}${metric('Trainings',m.training,'Upcoming sessions')}</section><section class="grid-2"><div class="card"><div class="card-head"><div><h3>Upcoming celebrations</h3><p>Birthdays coming up next</p></div><button class="button small ghost right" data-page-jump="members">View members</button></div><div class="card-body list">${upcoming.map(x=>`<div class="list-item"><div class="date-tile"><b>${x.next.toLocaleDateString('en-NG',{month:'short'}).toUpperCase()}</b><strong>${x.next.getDate()}</strong></div><div class="grow"><strong>${esc(x.name)}</strong><small>${esc(x.subunit)} · Birthday</small></div><span class="pill active">${daysUntil(x.next)} days</span></div>`).join('')||empty('No birthdays recorded')}</div></div><div class="card"><div class="card-head"><div><h3>Quick actions</h3><p>Keep your records moving</p></div></div><div class="card-body quick-actions"><button class="quick-action" data-add="member"><span>＋ Add member</span><small>Grow the directory</small></button><button class="quick-action" data-add="activity"><span>＋ Plan activity</span><small>Meeting or training</small></button><button class="quick-action" data-add="design"><span>＋ Add design</span><small>Track creative work</small></button></div></div></section><section class="grid-2 grid-even" style="margin-top:18px"><div class="card"><div class="card-head"><div><h3>Next activities</h3><p>Department calendar</p></div></div><div class="card-body list">${state.activities.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4).map(a=>`<div class="list-item"><div class="date-tile"><b>${dateFmt(a.date,{month:'short'}).toUpperCase()}</b><strong>${new Date(a.date+'T00:00:00').getDate()}</strong></div><div class="grow"><strong>${esc(a.title)}</strong><small>${esc(a.venue)} · ${esc(a.time)}</small></div><span class="pill ${a.status.toLowerCase().replace(' ','-')}">${esc(a.status)}</span></div>`).join('')||empty('No activities yet')}</div></div>${skillsCard()}</section>`},
members(){return `${tools('Search members…','member',['All status','Active','Inactive'])}<div class="card"><div class="card-head"><div><h3>Member directory</h3><p>${state.members.length} people recorded</p></div><button class="button small ghost right" id="csvMembers">↓ CSV export</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Member</th><th>Contact</th><th>Role / Sub-unit</th><th>Birthday</th><th>Skills</th><th>Status</th><th></th></tr></thead><tbody>${state.members.map(x=>`<tr data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${x.status}"><td><div class="person"><span class="person-badge">${initials(x.name)}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.functions||'No functions')}</small></div></div></td><td>${esc(x.phone)}<br><small>${esc(x.email)}</small></td><td><strong>${esc(x.role)}</strong><br><small>${esc(x.subunit)}</small></td><td>${dateFmt(x.birthday,{day:'numeric',month:'short'})}</td><td>${esc(x.skills||'—')}</td><td><span class="pill ${x.status.toLowerCase()}">${x.status}</span></td>${rowActions('member',x.id)}</tr>`).join('')}</tbody></table></div></div><div style="margin-top:18px">${skillsCard()}</div>`},
contributions(){let expected=state.contributionTypes.reduce((s,c)=>s+Number(c.amount)*state.members.length,0),received=state.payments.reduce((s,p)=>s+Number(p.amount),0),pct=expected?Math.round(received/expected*100):0;return `<div class="summary-strip">${summary('Expected',money(expected))}${summary('Received',money(received))}${summary('Outstanding',money(expected-received))}${summary('Collected',pct+'%')}</div><div class="page-tools"><button class="button primary" data-add="contribution">＋ Contribution type</button><button class="button gold" data-add="payment">＋ Record payment</button><span class="spacer"></span></div><div class="grid-2 grid-even"><div class="card"><div class="card-head"><div><h3>Contribution types</h3><p>Expected amount is per active member</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Contribution</th><th>Expected</th><th>Received</th><th>Progress</th><th></th></tr></thead><tbody>${state.contributionTypes.map(c=>{let got=state.payments.filter(p=>p.typeId===c.id).reduce((s,p)=>s+Number(p.amount),0),exp=Number(c.amount)*state.members.length,pc=exp?Math.round(got/exp*100):0;return `<tr><td><strong>${esc(c.name)}</strong><br><small>Due ${dateFmt(c.due)}</small></td><td>${money(exp)}</td><td>${money(got)}</td><td>${pc}%<div class="progress"><i style="width:${Math.min(pc,100)}%"></i></div></td>${rowActions('contribution',c.id)}</tr>`}).join('')||`<tr><td colspan="5">${empty('No contribution types')}</td></tr>`}</tbody></table></div></div><div class="card"><div class="card-head"><div><h3>Recent payments</h3><p>Individual member payments</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Member</th><th>Contribution</th><th>Amount</th><th>Date</th><th></th></tr></thead><tbody>${state.payments.slice().reverse().map(p=>`<tr><td>${esc(memberName(p.memberId))}</td><td>${esc(typeName(p.typeId))}</td><td><strong>${money(p.amount)}</strong></td><td>${dateFmt(p.date)}</td>${rowActions('payment',p.id)}</tr>`).join('')||`<tr><td colspan="5">${empty('No payments yet')}</td></tr>`}</tbody></table></div></div></div>`},
activities(){return `${tools('Search activities…','activity',['All status','Planned','In Progress','Completed'])}<div class="card"><div class="card-head"><div><h3>Department activities</h3><p>Meetings, trainings, outreaches and events</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Activity</th><th>Type</th><th>Date & time</th><th>Venue</th><th>Coordinator</th><th>Status</th><th></th></tr></thead><tbody>${state.activities.map(x=>`<tr data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${x.status}"><td><strong>${esc(x.title)}</strong><br><small>${esc(x.notes)}</small></td><td>${esc(x.type)}</td><td>${dateFmt(x.date)} · ${esc(x.time)}</td><td>${esc(x.venue)}</td><td>${esc(x.coordinator)}</td><td><span class="pill ${x.status.toLowerCase().replace(' ','-')}">${x.status}</span></td>${rowActions('activity',x.id)}</tr>`).join('')}</tbody></table></div></div>`},
schedule(){return `<div class="page-tools"><button class="button primary" data-add="schedule">＋ Meeting schedule</button><button class="button gold" data-add="roster">＋ Work roster</button></div><div class="grid-2 grid-even"><div class="card"><div class="card-head"><div><h3>Meeting schedules</h3><p>Agendas ready to share and print</p></div></div><div class="card-body list">${state.schedules.map(x=>recordItem(x,'schedule','Meeting agenda',x.date,x.venue)).join('')||empty('No schedules yet')}</div></div><div class="card"><div class="card-head"><div><h3>Work rosters</h3><p>Team assignments for events</p></div></div><div class="card-body list">${state.rosters.map(x=>recordItem(x,'roster','Duty roster',x.date,x.venue,x.event)).join('')||empty('No rosters yet')}</div></div></div>`},
designs(){return `${tools('Search designs…','design',['All status','Pending','In Progress','Approved'])}<div class="design-grid">${state.designs.map(x=>`<article class="design-card" data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${x.status}"><div class="design-thumb" ${x.thumbnail?`style="background-image:url('${esc(x.thumbnail)}');background-size:cover;background-position:center"`:''}><span>${x.thumbnail?'':esc(x.category)}</span></div><div class="design-info"><span class="pill ${x.status.toLowerCase().replace(' ','-')}">${esc(x.status)}</span><h4>${esc(x.title)}</h4><p>${dateFmt(x.date)} · ${esc(x.person)}</p><div class="actions"><a class="button small ghost" href="${esc(x.canva||'#')}" target="_blank" rel="noopener">Open Canva</a><button class="button small" data-edit="design" data-id="${x.id}">Edit</button><button class="button small danger" data-delete="design" data-id="${x.id}">Delete</button></div></div></article>`).join('')||empty('No designs yet')}</div>`},
reports(){return `<div class="notice">Reports reflect the information currently saved in this browser. Create a JSON backup regularly if you use more than one device.</div><div class="report-options"><div class="report-option"><div class="report-icon">▥</div><div><h4>Dashboard report</h4><p>Summary metrics, activities and celebrations</p></div><button class="button small primary" data-report="dashboard">Print / PDF</button></div><div class="report-option"><div class="report-icon">CSV</div><div><h4>Members table</h4><p>All member fields in spreadsheet format</p></div><button class="button small primary" id="csvMembers">Download</button></div><div class="report-option"><div class="report-icon">JSON</div><div><h4>Complete data backup</h4><p>Portable copy of every record</p></div><button class="button small primary" id="reportBackup">Download</button></div><div class="report-option"><div class="report-icon">↺</div><div><h4>Restore backup</h4><p>Replace this device's records from JSON</p></div><label class="button small primary file-label">Choose file<input id="reportRestore" type="file" accept="application/json"></label></div></div><div style="margin-top:18px" class="card"><div class="card-head"><div><h3>Data overview</h3><p>Current browser storage</p></div></div><div class="summary-strip" style="margin:18px;border:0">${summary('Members',state.members.length)}${summary('Activities',state.activities.length)}${summary('Schedules & rosters',state.schedules.length+state.rosters.length)}${summary('Designs',state.designs.length)}</div></div>`}}
const originalDashboard=views.dashboard;
views.dashboard=()=>originalDashboard().replace(`<div class="card-body quick-actions"><button class="quick-action" data-add="member"><span>＋ Add member</span><small>Grow the directory</small></button><button class="quick-action" data-add="activity"><span>＋ Plan activity</span><small>Meeting or training</small></button><button class="quick-action" data-add="design"><span>＋ Add design</span><small>Track creative work</small></button></div>`,`<div class="card-body quick-actions"><button class="quick-action" data-add="member"><span>＋ Add member</span><small>Grow the directory</small></button><button class="quick-action" data-add="activity"><span>＋ Schedule activity</span><small>Add to the calendar</small></button><button class="quick-action" data-add="contribution"><span>＋ Add contribution</span><small>Create a collection</small></button><button class="quick-action" data-add="payment"><span>＋ Record payment</span><small>Update contribution progress</small></button><button class="quick-action" data-add="design"><span>＋ Add design</span><small>Track creative work</small></button><button class="quick-action" data-page-jump="schedule"><span>✎ Edit schedule</span><small>Agenda and work roster</small></button></div>`)+contributionProgress('Dashboard contribution progress');
views.members=()=>`${tools('Search members…','member',['All status','Active','Inactive'])}<div class="card"><div class="card-head"><div><h3>Member directory</h3><p>${state.members.length} people recorded</p></div><button class="button small ghost right" id="csvMembers">↓ CSV export</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Member</th><th>Contact</th><th>Sub-unit</th><th>Birthday</th><th>Skill level</th><th>Status</th><th></th></tr></thead><tbody>${state.members.map(x=>`<tr data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${x.status}"><td><div class="person"><span class="person-badge">${initials(x.name)}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.email)}</small></div></div></td><td>${esc(x.phone)}</td><td>${esc(x.subunit)}</td><td>${dateFmt(x.birthday,{day:'numeric',month:'short'})}</td><td><strong>${esc(x.skill||'—')}</strong><br><small>${esc(x.skillLevel||'—')}</small></td><td><span class="pill ${x.status.toLowerCase()}">${x.status}</span></td>${rowActions('member',x.id)}</tr>`).join('')}</tbody></table></div></div><div style="margin-top:18px">${skillsCard()}</div>`;
views.contributions=()=>`${contributionProgress('Contribution progress')}<div class="page-tools"><button class="button primary" data-add="contribution">＋ Contribution type</button><button class="button gold" data-add="payment">＋ Record payment</button></div><div class="card"><div class="card-head"><div><h3>Individual contributions</h3><p>Expected amount and collection progress for each contribution</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Contribution</th><th>Per member</th><th>Expected</th><th>Received</th><th>Outstanding</th><th>Progress</th><th></th></tr></thead><tbody>${state.contributionTypes.map(c=>{let got=state.payments.filter(p=>p.typeId===c.id).reduce((s,p)=>s+Number(p.amount),0),exp=Number(c.amount)*state.members.length,pc=exp?Math.round(got/exp*100):0;return `<tr><td><strong>${esc(c.name)}</strong><br><small>Due ${dateFmt(c.due)}</small></td><td>${money(c.amount)}</td><td>${money(exp)}</td><td>${money(got)}</td><td>${money(exp-got)}</td><td>${pc}%<div class="progress"><i style="width:${Math.min(pc,100)}%"></i></div></td>${rowActions('contribution',c.id)}</tr>`}).join('')||`<tr><td colspan="7">${empty('No contribution types')}</td></tr>`}</tbody></table></div></div>`;
views.activities=()=>calendarView();
views.schedule=()=>templateView();
views.designs=()=>`${tools('Search designs…','design',['All status','Pending','Close to post date','Past'])}<div class="design-grid">${state.designs.map(x=>{let status=designStatus(x),title=x.memberId?memberName(x.memberId):x.title;return `<article class="design-card" data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${status}"><div class="design-thumb"><span>${esc(x.category)}</span></div><div class="design-info"><span class="pill ${status.toLowerCase().replaceAll(' ','-')}">${status}</span><h4>${esc(title||'Untitled design')}</h4><p>${dateFmt(x.date)} · ${esc(x.category)}</p><div class="actions"><a class="button small ghost" href="${esc(x.canva||'#')}" target="_blank" rel="noopener">Open Canva</a><button class="button small" data-edit="design" data-id="${x.id}">Edit</button><button class="button small danger" data-delete="design" data-id="${x.id}">Delete</button></div></div></article>`}).join('')||empty('No designs yet')}</div>`;
function contributionProgress(title){return `<section class="card" style="margin:18px 0"><div class="card-head"><div><h3>${title}</h3><p>Each contribution is measured independently</p></div></div><div class="contribution-metrics">${state.contributionTypes.map(c=>{let exp=Number(c.amount)*state.members.length,got=state.payments.filter(p=>p.typeId===c.id).reduce((s,p)=>s+Number(p.amount),0),pc=exp?Math.round(got/exp*100):0;return `<div class="contribution-stat"><span>${esc(c.name)}</span><strong>${pc}%</strong><small>${money(got)} of ${money(exp)}</small><div class="progress"><i style="width:${Math.min(pc,100)}%"></i></div></div>`}).join('')||empty('Add a contribution to see its progress')}</div></section>`}
function calendarView(){let types=['All','Training','Outreach','Event','Evangelism','Meeting','Hangout'],filtered=state.activities.filter(a=>activityTypeFilter==='All'||a.type===activityTypeFilter),y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay(),cells=[];for(let i=0;i<offset;i++)cells.push('<div class="calendar-day muted"></div>');for(let d=1;d<=days;d++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,items=state.activities.filter(a=>a.date===iso);cells.push(`<button class="calendar-day" data-calendar-date="${iso}"><b>${d}</b>${items.map(a=>`<span>${esc(a.time)} ${esc(a.title)}</span>`).join('')}<i>＋ Schedule</i></button>`)}return `<div class="calendar-toolbar"><select class="filter" id="activityTypeFilter">${types.map(t=>`<option ${t===activityTypeFilter?'selected':''}>${t}</option>`).join('')}</select><span class="spacer"></span><button class="button primary" data-add="activity">＋ Add activity</button></div><div class="card activity-results"><div class="card-head"><div><h3>${activityTypeFilter} activities</h3><p>${filtered.length} matching result${filtered.length===1?'':'s'}</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Activity</th><th>Type</th><th>Date & time</th><th>Venue</th><th>Status</th><th></th></tr></thead><tbody>${filtered.sort((a,b)=>a.date.localeCompare(b.date)).map(a=>`<tr><td><strong>${esc(a.title)}</strong></td><td>${esc(a.type)}</td><td>${dateFmt(a.date)} · ${esc(a.time)}</td><td>${esc(a.venue)}</td><td><span class="pill ${a.status.toLowerCase().replace(' ','-')}">${a.status}</span></td>${rowActions('activity',a.id)}</tr>`).join('')||`<tr><td colspan="6">${empty('No matching activities')}</td></tr>`}</tbody></table></div></div><div class="calendar-toolbar calendar-heading"><button class="button ghost" data-calendar-nav="-1">←</button><h2>${first.toLocaleDateString('en-NG',{month:'long',year:'numeric'})}</h2><button class="button ghost" data-calendar-nav="1">→</button></div><div class="calendar"><div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div>`}
function templateView(){let s=state.schedules[0]||{id:id('s'),title:'Meeting Agenda',date:'',time:'',venue:'',coordinator:'',theme:'',notes:'',agenda:''},r=state.rosters[0]||{id:id('r'),event:'Work Roster',date:'',venue:'',coordinator:'',notes:'',assignments:''};if(!state.schedules.length)state.schedules.push(s);if(!state.rosters.length)state.rosters.push(r);return `<div class="template-stack">${editableTemplate('schedule',s)}${editableTemplate('roster',r)}</div>`}
function editableTemplate(type,x){if(type==='roster')return displayScheduleTemplate(x);let rows=parseRows(x.agenda,6),heads=['Start','End','Activity','Description','Responsible','Notes'];while(rows.length<4)rows.push(Array(heads.length).fill(''));return `<section class="card editable-template" data-template="${type}" data-id="${x.id}"><div class="card-head"><div><p class="eyebrow">EDITABLE MEETING TEMPLATE</p><h3 contenteditable="true" data-key="title">${esc(x.title)}</h3></div><div class="right"><button class="button small ghost" data-export="${type}" data-id="${x.id}">Export</button><button class="button small primary" data-save-template="${type}">Save template</button></div></div><div class="card-body"><div class="template-meta">${[['date','Date'],['venue','Venue'],['coordinator','Coordinator'],['theme','Theme']].map(([k,l])=>`<label>${l}<input type="${k==='date'?'date':'text'}" data-key="${k}" value="${esc(x[k]||'')}"></label>`).join('')}</div><div class="table-wrap"><table class="data-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((row,ri)=>`<tr>${row.map((v,ci)=>`<td contenteditable="true" data-cell="${ri},${ci}">${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><label class="template-notes">Notes<textarea data-key="notes">${esc(x.notes||'')}</textarea></label></div></section>`}
function displayScheduleTemplate(x){let rows=parseRows(x.assignments,5);if(rows.length!==4||rows.some(r=>r.length!==5))rows=[['First Service','Praise & Choir Ministration','','',''],['First Service','Word','','',''],['Second Service','Praise & Choir Ministration','','',''],['Second Service','Word','','','']];return `<section class="display-schedule editable-template" data-template="roster" data-id="${x.id}"><div class="display-actions"><div><p>EDITABLE WORK SCHEDULE</p><h3 contenteditable="true" data-key="event">${esc(x.event||'Display Schedule')}</h3></div><div><button class="button small ghost" data-export="roster" data-id="${x.id}">Export portrait JPG / PDF</button><button class="button small gold" data-save-template="roster">Save schedule</button></div></div><label class="display-date">Schedule date <input type="date" data-key="date" value="${esc(x.date||'')}"></label><div class="display-table"><div class="display-head"><span>Service</span><span>Ministration</span><span>▣ Side Screen</span><span>▣ Middle Screen</span><span>▤ Scripture Assistance</span></div>${rows.map((row,ri)=>`<div class="display-row ${ri===2?'service-break':''}">${row.map((v,ci)=>`<span contenteditable="true" data-cell="${ri},${ci}">${esc(v)}</span>`).join('')}</div>`).join('')}</div><label class="display-notes">Notes<textarea data-key="notes">${esc(x.notes||'')}</textarea></label></section>`}
displayScheduleTemplate=function(x){let rows=parseRows(x.assignments,5),heads=['Service','Ministration','Side Screen','Middle Screen','Scripture Assistance'];if(rows.length!==4||rows.some(r=>r.length!==5))rows=[['First Service','Praise & Choir Ministration','','',''],['First Service','Word','','',''],['Second Service','Praise & Choir Ministration','','',''],['Second Service','Word','','','']];return `<section class="card editable-template work-template" data-template="roster" data-id="${x.id}"><div class="card-head"><div><p class="eyebrow">EDITABLE WORK SCHEDULE</p><h3 contenteditable="true" data-key="event">${esc(x.event||'Display Schedule')}</h3></div><div class="right"><button class="button small ghost" data-export="roster" data-id="${x.id}">Export portrait JPG / PDF</button><button class="button small primary" data-save-template="roster">Save schedule</button></div></div><div class="card-body"><div class="template-meta"><label>Date<input type="date" data-key="date" value="${esc(x.date||'')}"></label></div><div class="table-wrap"><table class="data-table schedule-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((row,ri)=>`<tr class="${ri===2?'service-break':''}">${row.map((v,ci)=>`<td contenteditable="true" data-cell="${ri},${ci}">${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><label class="template-notes">Notes<textarea data-key="notes">${esc(x.notes||'')}</textarea></label></div></section>`}
function saveTemplate(button){let box=button.closest('[data-template]'),type=box.dataset.template,col=collection(type),x=state[col].find(v=>v.id===box.dataset.id),fields=box.querySelectorAll('[data-key]');fields.forEach(el=>x[el.dataset.key]=el.value??el.textContent.trim());let rows=[...box.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(td=>td.textContent.trim()).join('|')).filter(r=>r.replaceAll('|','').trim());x[type==='schedule'?'agenda':'assignments']=rows.join('\n');save('Template saved')}
function designStatus(x){let target=new Date((x.date||'2999-01-01')+'T23:59:59'),now=new Date(),days=Math.ceil((target-now)/86400000);return days<0?'Past':days<=3?'Close to post date':'Pending'}
const NOTIFICATION_READ_KEY='illuminate-read-notifications';
function notificationReadSet(){try{return new Set(JSON.parse(localStorage.getItem(NOTIFICATION_READ_KEY)||'[]'))}catch{return new Set()}}
function notificationCenterItems(){let now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),items=[];state.members.forEach(member=>{if(!member.birthday)return;let next=nextBirthday(member.birthday),days=Math.ceil((next-today)/86400000);if(days<=30)items.push({key:`birthday:${member.id}:${next.getFullYear()}`,type:'Birthday',title:`${member.name}'s birthday`,body:days===0?'Celebration is today':`Coming up in ${days} day${days===1?'':'s'}`,date:next,page:'members',icon:'♢'})});state.activities.forEach(activity=>{let date=new Date(activity.date+'T00:00:00'),days=Math.ceil((date-today)/86400000);if(days>=0&&days<=30)items.push({key:`activity:${activity.id}:${activity.date}`,type:activity.type,title:activity.title,body:`${dateFmt(activity.date)} · ${activity.time||'Time not set'} · ${activity.venue||'Venue not set'}`,date,page:'activities',icon:'◷'})});state.contributionTypes.forEach(item=>{if(!item.due||item.status!=='Active')return;let date=new Date(item.due+'T00:00:00'),days=Math.ceil((date-today)/86400000);if(days>=-7&&days<=14)items.push({key:`contribution:${item.id}:${item.due}`,type:'Contribution',title:item.name,body:days<0?`Deadline passed ${Math.abs(days)} day${Math.abs(days)===1?'':'s'} ago`:days===0?'Deadline is today':`Due in ${days} day${days===1?'':'s'}`,date,page:'contributions',icon:'₦'})});state.designs.forEach(design=>{if(!design.date)return;let date=new Date(design.date+'T00:00:00'),days=Math.ceil((date-today)/86400000),title=design.memberId?memberName(design.memberId):design.title;if(days>=-7&&days<=14)items.push({key:`design:${design.id}:${design.date}`,type:'Design',title:title||'Scheduled design',body:days<0?`Post date passed ${Math.abs(days)} day${Math.abs(days)===1?'':'s'} ago`:days===0?'Scheduled to post today':`Scheduled in ${days} day${days===1?'':'s'}`,date,page:'designs',icon:'◇'})});return items.sort((a,b)=>a.date-b.date)}
function updateNotificationBadge(){let count=document.getElementById('notificationCount');if(!count)return;let read=notificationReadSet(),unread=notificationCenterItems().filter(item=>!read.has(item.key)).length;count.textContent=unread>99?'99+':unread;count.hidden=unread===0}
function markNotificationRead(key){let read=notificationReadSet();read.add(key);localStorage.setItem(NOTIFICATION_READ_KEY,JSON.stringify([...read]));updateNotificationBadge()}
function markAllNotificationsRead(){localStorage.setItem(NOTIFICATION_READ_KEY,JSON.stringify(notificationCenterItems().map(item=>item.key)));render();toast('All notifications marked as read')}
views.notifications=()=>{let items=notificationCenterItems(),read=notificationReadSet();return `<div class="page-tools"><p class="notification-summary">Upcoming reminders and recent deadlines</p><span class="spacer"></span><button class="button ghost" id="markAllNotifications">Mark all as read</button></div><section class="card notification-page"><div class="card-head"><div><h3>Notification center</h3><p>${items.filter(item=>!read.has(item.key)).length} unread · ${items.length} total</p></div></div><div class="notification-list">${items.map(item=>`<button class="notification-item ${read.has(item.key)?'read':'unread'}" data-notification-key="${esc(item.key)}" data-notification-page="${item.page}"><span class="notification-type-icon">${item.icon}</span><span class="notification-copy"><small>${esc(item.type)}</small><strong>${esc(item.title)}</strong><span>${esc(item.body)}</span></span><time>${dateFmt(item.date.toISOString().slice(0,10),{day:'numeric',month:'short'})}</time></button>`).join('')||empty('You have no upcoming reminders')}</div></section>`}
views.designs=()=>`${tools('Search designs…','design',['All status','Pending','Close to post date','Past'])}<div class="design-grid">${state.designs.map(x=>{let status=designStatus(x),title=x.memberId?memberName(x.memberId):x.title;return `<article class="design-card" data-search="${esc(Object.values(x).join(' ').toLowerCase())}" data-status="${status}"><div class="design-thumb"><span>${esc(x.category)}</span></div><div class="design-info"><span class="pill ${status.toLowerCase().replaceAll(' ','-')}">${status}</span><h4>${esc(title||'Untitled design')}</h4><p>${dateFmt(x.date)} · ${esc(x.category)}</p><div class="design-file"><span>${x.fileName?'▣':'○'}</span><div><strong>${esc(x.fileName||'No file uploaded')}</strong><small>${x.fileSize?formatBytes(x.fileSize):'Edit this design to upload a file'}</small></div></div><div class="actions">${x.filePath?`<button class="button small gold" data-download-design="${x.id}">Download</button>`:''}<button class="button small" data-edit="design" data-id="${x.id}">Edit</button><button class="button small danger" data-delete="design" data-id="${x.id}">Delete</button></div></div></article>`}).join('')||empty('No designs yet')}</div>`;
function formatBytes(value){if(!value)return '';let units=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),3);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
function metric(a,b,c){return `<div class="metric"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`}function summary(a,b){return `<div class="summary-cell"><span>${a}</span><strong>${b}</strong></div>`}function empty(t){return `<div class="empty"><div class="empty-icon">◇</div>${t}</div>`}
function tools(ph,type,statuses){return `<div class="page-tools"><input class="search" id="searchInput" placeholder="${ph}" aria-label="${ph}"><select class="filter" id="statusFilter">${statuses.map(x=>`<option>${x}</option>`).join('')}</select><span class="spacer"></span><button class="button primary" data-add="${type}">＋ Add ${type}</button></div>`}
function rowActions(type,id){return `<td><div class="actions"><button class="action" data-edit="${type}" data-id="${id}">Edit</button><button class="action danger" data-delete="${type}" data-id="${id}">Delete</button></div></td>`}
function recordItem(x,type,label,date,venue,title=x.title){return `<div class="list-item"><div class="date-tile"><b>${dateFmt(date,{month:'short'}).toUpperCase()}</b><strong>${new Date(date+'T00:00:00').getDate()}</strong></div><div class="grow"><strong>${esc(title)}</strong><small>${label} · ${esc(venue)}</small></div><div class="actions"><button class="button small ghost" data-export="${type}" data-id="${x.id}">Export</button><button class="action" data-edit="${type}" data-id="${x.id}">Edit</button><button class="action danger" data-delete="${type}" data-id="${x.id}">Delete</button></div></div>`}
function skillsCard(){let names=['General schedule','Scripture Projection','using VMIX'],levels=['Beginner','Intermediate','Advanced'];return `<div class="card"><div class="card-head"><div><h3>Skill matrix</h3><p>Members by approved skill and level</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Skill</th>${levels.map(l=>`<th>${l}</th>`).join('')}<th>Total</th></tr></thead><tbody>${names.map(skill=>{let ms=state.members.filter(m=>m.skill===skill);return `<tr><td><strong>${skill}</strong></td>${levels.map(l=>`<td>${ms.filter(m=>m.skillLevel===l).length}</td>`).join('')}<td><strong>${ms.length}</strong></td></tr>`}).join('')}</tbody></table></div></div>`}
function bindView(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openForm(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(b.dataset.edit,b.dataset.id));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete,b.dataset.id));document.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>{current=b.dataset.pageJump;render()});document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportRecord(b.dataset.export,b.dataset.id));document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>printDashboard());document.querySelectorAll('[data-calendar-date]').forEach(b=>b.onclick=()=>{openForm('activity');document.querySelector('[name="date"]').value=b.dataset.calendarDate});document.querySelectorAll('[data-calendar-nav]').forEach(b=>b.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+Number(b.dataset.calendarNav));render()});document.querySelectorAll('[data-save-template]').forEach(b=>b.onclick=()=>saveTemplate(b));let atf=document.getElementById('activityTypeFilter');if(atf)atf.onchange=()=>{activityTypeFilter=atf.value;render()};let s=document.getElementById('searchInput'),f=document.getElementById('statusFilter');if(s)s.oninput=filterRows;if(f)f.onchange=filterRows;document.querySelectorAll('#csvMembers').forEach(b=>b.onclick=csvMembers);let rb=document.getElementById('reportBackup');if(rb)rb.onclick=backup;let rr=document.getElementById('reportRestore');if(rr)rr.onchange=restore}
function filterRows(){let q=(document.getElementById('searchInput')?.value||'').toLowerCase(),f=document.getElementById('statusFilter')?.value||'All status';document.querySelectorAll('[data-search]').forEach(r=>r.style.display=(r.dataset.search.includes(q)&&(f==='All status'||r.dataset.status===f))?'':'none')}
const schemas={member:[['name','Name','text'],['phone','Phone','tel'],['email','Email','email'],['birthday','Birthday','date'],['status','Status','select','Active|Inactive'],['role','Role','text'],['subunit','Sub-unit','text'],['skills','Skills and levels','text','e.g. Canva:Advanced, Photography:Intermediate'],['functions','Functions','text'],['trainings','Trainings','text'],['notes','Notes','textarea']],contribution:[['name','Contribution name','text'],['amount','Expected amount per member (₦)','number'],['due','Due date','date'],['status','Status','select','Active|Closed']],payment:[['typeId','Contribution','selectType'],['memberId','Member','selectMember'],['amount','Amount paid (₦)','number'],['date','Payment date','date']],activity:[['title','Activity title','text'],['type','Type','select','Meeting|Training|Outreach|Event'],['date','Date','date'],['time','Time','time'],['venue','Venue','text'],['coordinator','Coordinator','text'],['status','Status','select','Planned|In Progress|Completed'],['notes','Notes','textarea']],schedule:[['title','Meeting title','text'],['date','Date','date'],['time','Time','time'],['venue','Venue','text'],['coordinator','Coordinator','text'],['theme','Theme','text'],['agenda','Agenda items','textarea','One item per line: Start|End|Activity|Description|Responsible|Notes'],['notes','General notes','textarea']],roster:[['event','Event title','text'],['date','Date','date'],['venue','Venue','text'],['coordinator','Coordinator','text'],['assignments','Duty assignments','textarea','One per line: Function|Member|Backup|Reporting time|Duty time|Location|Status|Notes'],['notes','General notes','textarea']],design:[['title','Design title','text'],['category','Category','select','Birthday|Wedding Anniversary|Event|Announcement|Other'],['date','Scheduled date','date'],['person','Person / celebration','text'],['canva','Canva link','url'],['thumbnail','Thumbnail image link','url'],['status','Status','select','Pending|In Progress|Approved'],['notes','Notes','textarea']]};
schemas.member=[['name','Name','text'],['phone','Phone','tel'],['email','Email','email'],['birthday','Birthday','date'],['status','Status','select','Active|Inactive'],['subunit','Sub-unit','select','Finance|Admin|Technical|Member|Welfare'],['skill','Skill','select','General schedule|Scripture Projection|using VMIX'],['skillLevel','Skill level','select','Beginner|Intermediate|Advanced'],['notes','Notes','textarea']];
schemas.activity=[['title','Activity title','text'],['type','Type','select','Training|Outreach|Event|Evangelism|Meeting|Hangout'],['date','Date','date'],['time','Time','time'],['venue','Venue','text'],['coordinator','Coordinator','text'],['status','Status','select','Planned|In Progress|Completed'],['notes','Notes','textarea']];
schemas.design=[['memberId','Member (optional)','selectMemberOptional'],['title','Title when not for a member','text'],['category','Category','select','Birthday|Wedding Anniversary|Event|Announcement|Other'],['date','Scheduled / design date','date'],['file','Design file','file','Upload JPG, PNG, PDF, or another finished design file (maximum 50 MB).'],['notes','Notes','textarea']];
function collection(type){return type==='contribution'?'contributionTypes':type==='payment'?'payments':type==='activity'?'activities':type==='schedule'?'schedules':type==='roster'?'rosters':type==='design'?'designs':'members'}
function openForm(type,recordId){let data=recordId?state[collection(type)].find(x=>x.id===recordId):{};editContext={type,recordId};document.getElementById('modalEyebrow').textContent=recordId?'EDIT RECORD':'NEW RECORD';document.getElementById('modalTitle').textContent=`${recordId?'Edit':'Add'} ${type}`;document.getElementById('modalBody').innerHTML=`<div class="form-grid">${schemas[type].map(([n,l,t,opt])=>field(n,l,t,data[n]??'',opt)).join('')}</div>`;document.getElementById('modal').showModal()}
function field(n,l,t,v,opt){let input=t==='textarea'?`<textarea name="${n}" ${n==='agenda'||n==='assignments'?'rows="7"':''}>${esc(v)}</textarea>`:t==='select'?`<select name="${n}">${opt.split('|').map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select>`:t==='selectMember'?`<select name="${n}">${state.members.map(m=>`<option value="${m.id}" ${m.id===v?'selected':''}>${esc(m.name)}</option>`).join('')}</select>`:t==='selectMemberOptional'?`<select name="${n}"><option value="">Not for a member</option>${state.members.map(m=>`<option value="${m.id}" ${m.id===v?'selected':''}>${esc(m.name)}</option>`).join('')}</select>`:t==='selectType'?`<select name="${n}">${state.contributionTypes.map(c=>`<option value="${c.id}" ${c.id===v?'selected':''}>${esc(c.name)}</option>`).join('')}</select>`:t==='file'?`<input name="${n}" type="file" accept="image/*,.pdf,.zip,.ppt,.pptx,.psd,.ai,.svg">`:`<input name="${n}" type="${t}" value="${esc(v)}" ${n==='name'?'required':''}>`;return `<div class="field ${t==='textarea'||t==='file'?'full':''}"><label>${l}</label>${input}${opt&&t!=='select'?`<span class="hint">${opt}</span>`:''}</div>`}
function storagePath(path){return String(path).split('/').map(encodeURIComponent).join('/')}
async function uploadDesignFile(file){if(!cloudSession)throw new Error('Sign in before uploading a design');if(file.size>52428800)throw new Error('The file is larger than 50 MB');let safe=file.name.replace(/[^a-zA-Z0-9._,'!&$@=;()+?-]+/g,'-'),path=`${new Date().toISOString().slice(0,10)}/${Date.now()}-${safe}`,response=await fetch(`${SUPABASE_URL}/storage/v1/object/design-files/${storagePath(path)}`,{method:'POST',headers:{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${cloudSession.access_token}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!response.ok){let data=await response.json().catch(()=>({}));throw new Error(data.message||data.error||'File upload failed')}return {filePath:path,fileName:file.name,fileType:file.type||'application/octet-stream',fileSize:file.size}}
async function downloadDesignFile(recordId){let design=state.designs.find(x=>x.id===recordId);if(!design?.filePath){toast('No file has been uploaded for this design');return}try{let response=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/design-files/${storagePath(design.filePath)}`,{headers:{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${cloudSession.access_token}`}});if(!response.ok)throw new Error('Download failed');let blob=await response.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=design.fileName||'design-file';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Design file downloaded')}catch(error){toast(error.message)}}
async function deleteDesignFile(path){if(!path||!cloudSession)return;fetch(`${SUPABASE_URL}/storage/v1/object/design-files/${storagePath(path)}`,{method:'DELETE',headers:{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${cloudSession.access_token}`}}).catch(()=>{})}
document.getElementById('modalForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let button=document.getElementById('modalSave'),formData=new FormData(e.currentTarget),file=formData.get('file'),fd=Object.fromEntries(formData);delete fd.file;button.disabled=true;button.textContent=file?.size?'Uploading…':'Saving…';try{let col=collection(editContext.type),existing=editContext.recordId?state[col].find(x=>x.id===editContext.recordId):null;if(editContext.type==='design'&&file?.size){let uploaded=await uploadDesignFile(file);if(existing?.filePath)deleteDesignFile(existing.filePath);Object.assign(fd,uploaded)}if(editContext.recordId){let i=state[col].findIndex(x=>x.id===editContext.recordId);state[col][i]={...state[col][i],...fd}}else state[col].push({id:id(editContext.type[0]),...fd});document.getElementById('modal').close();save(file?.size?'File uploaded and design saved':'Record saved')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Save record'}});
function remove(type,recordId){if(!confirm('Delete this record? This cannot be undone unless you have a backup.'))return;let col=collection(type),record=state[col].find(x=>x.id===recordId);if(type==='design'&&record?.filePath)deleteDesignFile(record.filePath);state[col]=state[col].filter(x=>x.id!==recordId);if(type==='member')state.payments=state.payments.filter(x=>x.memberId!==recordId);if(type==='contribution')state.payments=state.payments.filter(x=>x.typeId!==recordId);save('Record deleted')}
function nextBirthday(v){if(!v)return new Date(2999,0,1);let d=new Date(v+'T00:00:00'),now=new Date(),n=new Date(now.getFullYear(),d.getMonth(),d.getDate());if(n<new Date(now.getFullYear(),now.getMonth(),now.getDate()))n.setFullYear(n.getFullYear()+1);return n}function daysUntil(d){return Math.max(0,Math.ceil((d-new Date())/86400000))}function memberName(x){return state.members.find(m=>m.id===x)?.name||'Unknown'}function typeName(x){return state.contributionTypes.find(c=>c.id===x)?.name||'Unknown'}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backup(){download(`illuminate-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({app:'Illuminate DMS',version:1,exportedAt:new Date().toISOString(),data:state},null,2),'application/json');toast('Backup downloaded')}
async function restore(e){let f=e.target.files[0];if(!f)return;try{let parsed=JSON.parse(await f.text()),data=parsed.data||parsed;if(!data.members||!Array.isArray(data.members))throw Error();if(confirm('Replace all current records with this backup?')){state={...structuredClone(seed),...data};save('Backup restored')}}catch{alert('This file is not a valid Illuminate backup.')}e.target.value=''}
function csvMembers(){let cols=['Name','Phone','Email','Birthday','Status','Sub-unit','Skill','Skill Level','Notes'],keys=['name','phone','email','birthday','status','subunit','skill','skillLevel','notes'],q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download(`illuminate-members-${new Date().toISOString().slice(0,10)}.csv`,[cols.map(q).join(','),...state.members.map(m=>keys.map(k=>q(m[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8');toast('Members CSV downloaded')}
function exportRecord(type,recordId){if(type==='roster'){exportDisplaySchedule(recordId);return}let x=state[collection(type)].find(v=>v.id===recordId),title=x.title,rows=parseRows(x.agenda,6),heads=['Start','End','Activity','Description','Responsible','Notes'];let html=`<!doctype html><html><head><title>${esc(title)}</title><style>@page{size:A4 portrait;margin:12mm}body{font-family:Arial;color:#172a46;padding:10px}header{border-bottom:3px solid #d7a928;margin-bottom:16px}small{letter-spacing:2px}h1{font-family:Georgia}table{border-collapse:collapse;width:100%;font-size:9px;table-layout:fixed}th,td{border:1px solid #cad2dc;padding:7px 5px;text-align:left;overflow-wrap:anywhere}th{background:#172a46;color:white}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0;font-size:11px}.notes{margin-top:16px;padding:10px;background:#f4f6f8}.no-print{margin-bottom:15px}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="print()">Print / Save PDF</button><header><small>DAVID'S CHRISTIAN CENTER · ILLUMINATE DEPARTMENT</small><h1>${esc(title)}</h1></header><div class="meta"><b>Date: ${dateFmt(x.date)}</b><b>Venue: ${esc(x.venue)}</b><b>Coordinator: ${esc(x.coordinator)}</b><b>Theme: ${esc(x.theme||'—')}</b></div><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${heads.map((_,i)=>`<td>${esc(r[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="notes"><b>Notes</b><p>${esc(x.notes||'No additional notes.')}</p></div></body></html>`;let win=open('','_blank');win.document.write(html);win.document.close();setTimeout(()=>win.print(),350);renderCanvasExport(title,x,heads,rows)}
function exportDisplaySchedule(recordId){let x=state.rosters.find(v=>v.id===recordId),rows=parseRows(x.assignments,5),html=`<!doctype html><html><head><title>${esc(x.event||'Display Schedule')}</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#090909;color:#fff;font-family:Arial;padding:12mm;min-height:297mm}button{padding:9px 13px;margin-bottom:10px}.title{text-align:center;margin:8mm 0 4mm}.title h1{font:italic 44px Georgia;margin:0}.title h2{font-size:27px;margin:7px 0}.box{border:1.5px solid #fff;border-radius:24px;overflow:hidden;margin-top:8mm}.grid{display:grid;grid-template-columns:1.05fr 1.45fr 1fr 1fr 1.15fr}.grid span{padding:13px 8px;border-right:2px solid #f4c400;text-align:center;min-height:52px;display:grid;place-items:center}.grid span:last-child{border-right:0}.head{color:#f4c400;font-weight:bold}.row{border-top:1px solid #fff}.row span:first-child{color:#f4c400;font-weight:bold}.break{border-top:2px solid #fff}.notes{margin:8mm 2mm;color:#ddd}@media print{button{display:none}}</style></head><body><button onclick="print()">Print / Save PDF</button><div class="title"><h1>${esc(x.event||'Display Schedule')}</h1><h2>${dateFmt(x.date,{day:'numeric',month:'long',year:'numeric'})}</h2></div><div class="box"><div class="grid head"><span>Service</span><span>Ministration</span><span>▣ Side Screen</span><span>▣ Middle Screen</span><span>▤ Scripture Assistance</span></div>${rows.map((r,i)=>`<div class="grid row ${i===2?'break':''}">${r.map(v=>`<span>${esc(v)}</span>`).join('')}</div>`).join('')}</div>${x.notes?`<div class="notes">${esc(x.notes)}</div>`:''}</body></html>`;let win=open('','_blank');win.document.write(html);win.document.close();setTimeout(()=>win.print(),350);renderDisplayScheduleJpg(x,rows)}
function renderDisplayScheduleJpg(x,rows){let c=document.createElement('canvas'),w=1200,h=1600,g=c.getContext('2d');c.width=w;c.height=h;g.fillStyle='#080808';g.fillRect(0,0,w,h);g.strokeStyle='#f4c400';g.lineWidth=2;for(let i=-200;i<w;i+=150){g.beginPath();g.moveTo(i,0);g.lineTo(i+500,h);g.strokeStyle='rgba(244,196,0,.055)';g.stroke()}g.textAlign='center';g.fillStyle='#fff';g.font='italic 74px Georgia';g.fillText(x.event||'Display Schedule',w/2,145);g.font='bold 42px Arial';g.fillText(dateFmt(x.date,{day:'numeric',month:'long',year:'numeric'}),w/2,215);let left=65,top=290,width=1070,colW=[190,300,190,190,200],rowH=150;g.strokeStyle='#fff';g.lineWidth=3;g.strokeRect(left,top,width,rowH*5);let xx=left;for(let i=0;i<4;i++){xx+=colW[i];g.strokeStyle='#f4c400';g.beginPath();g.moveTo(xx,top);g.lineTo(xx,top+rowH*5);g.stroke()}for(let i=1;i<5;i++){g.strokeStyle='#fff';g.beginPath();g.moveTo(left,top+i*rowH);g.lineTo(left+width,top+i*rowH);g.stroke()}let heads=['Service','Ministration','Side Screen','Middle Screen','Scripture Assistance'];xx=left;g.font='bold 20px Arial';heads.forEach((v,i)=>{g.fillStyle='#f4c400';wrapCanvas(g,v,xx+colW[i]/2,top+55,colW[i]-12,24);xx+=colW[i]});rows.forEach((r,ri)=>{xx=left;r.forEach((v,i)=>{g.fillStyle=i===0?'#f4c400':'#fff';g.font=`${i===0?'bold ':''}22px Arial`;wrapCanvas(g,v,xx+colW[i]/2,top+(ri+1)*rowH+48,colW[i]-16,28);xx+=colW[i]})});g.fillStyle='#ddd';g.font='18px Arial';g.textAlign='left';g.fillText((x.notes||'').slice(0,95),left,top+rowH*5+65);c.toBlob(b=>download(`${slug(x.event||'display-schedule')}.jpg`,b,'image/jpeg'),'image/jpeg',.94);toast('Display schedule JPG downloaded; use the print window for PDF')}
function wrapCanvas(g,text,x,y,maxWidth,lineHeight){let words=String(text||'').split(' '),line='',lines=[];for(let word of words){let test=line+word+' ';if(g.measureText(test).width>maxWidth&&line){lines.push(line.trim());line=word+' '}else line=test}lines.push(line.trim());lines.slice(0,3).forEach((l,i)=>g.fillText(l,x,y+i*lineHeight))}
function parseRows(text,n){return (text||'').split(/\n+/).filter(Boolean).map(l=>{let r=l.split('|');while(r.length<n)r.push('');return r})}
function renderCanvasExport(title,x,heads,rows){let w=1200,rowH=64,pad=55,h=Math.max(1680,315+(rows.length+1)*rowH+150),c=document.createElement('canvas');c.width=w;c.height=h;let g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,w,h);g.fillStyle='#172a46';g.fillRect(0,0,w,34);g.fillStyle='#d7a928';g.fillRect(0,34,w,8);g.fillStyle='#172a46';g.font='bold 17px Arial';g.fillText("DAVID'S CHRISTIAN CENTER · ILLUMINATE DEPARTMENT",pad,92);g.font='bold 39px Georgia';g.fillText(title.slice(0,42),pad,150);g.font='18px Arial';g.fillText(`Date: ${dateFmt(x.date)}   Venue: ${x.venue}`.slice(0,92),pad,202);g.fillText(`Coordinator: ${x.coordinator}`.slice(0,92),pad,234);let y=275,col=(w-pad*2)/heads.length;g.font='bold 12px Arial';heads.forEach((v,i)=>{g.fillStyle='#172a46';g.fillRect(pad+i*col,y,col,rowH);g.fillStyle='#fff';g.fillText(v.slice(0,15),pad+i*col+5,y+36)});y+=rowH;g.font='11px Arial';rows.forEach(r=>{r.forEach((v,i)=>{g.strokeStyle='#cdd4dd';g.strokeRect(pad+i*col,y,col,rowH);g.fillStyle='#172235';g.fillText(String(v||'').slice(0,18),pad+i*col+5,y+36)});y+=rowH});g.font='15px Arial';g.fillText(`Notes: ${x.notes||'No additional notes.'}`.slice(0,125),pad,y+48);c.toBlob(b=>download(`${slug(title)}.jpg`,b,'image/jpeg'),'image/jpeg',.92);toast('Portrait JPG downloaded; use the print window to save PDF')}
function printDashboard(){let m=metrics(),rows=state.contributionTypes.map(c=>{let exp=Number(c.amount)*state.members.length,got=state.payments.filter(p=>p.typeId===c.id).reduce((s,p)=>s+Number(p.amount),0);return `<tr><td>${esc(c.name)}</td><td>${money(exp)}</td><td>${money(got)}</td><td>${money(exp-got)}</td><td>${exp?Math.round(got/exp*100):0}%</td></tr>`}).join(''),levels=['Beginner','Intermediate','Advanced'],skillRows=['General schedule','Scripture Projection','using VMIX'].map(skill=>`<tr><td>${skill}</td>${levels.map(level=>`<td>${state.members.filter(x=>x.skill===skill&&x.skillLevel===level).length}</td>`).join('')}<td><b>${state.members.filter(x=>x.skill===skill).length}</b></td></tr>`).join(''),html=`<!doctype html><html><head><title>Illuminate Dashboard Report</title><style>@page{size:A4 portrait;margin:16mm}body{font-family:Arial;color:#172a46}header{border-bottom:3px solid #d7a928;margin-bottom:24px}h1,h2{font-family:Georgia}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metric{border:1px solid #dfe4ea;padding:15px}.metric b{display:block;font-size:25px;margin-top:7px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #dfe4ea;padding:9px;text-align:left;font-size:11px}th{background:#172a46;color:#fff}.no-print{margin-bottom:15px}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="print()">Print / Save PDF</button><header><small>DAVID'S CHRISTIAN CENTER · ILLUMINATE DEPARTMENT</small><h1>Dashboard Report</h1><p>${new Date().toLocaleDateString('en-NG',{dateStyle:'long'})}</p></header><div class="metrics"><div class="metric">Total members<b>${state.members.length}</b></div><div class="metric">Active members<b>${m.active}</b></div><div class="metric">Inactive members<b>${m.inactive}</b></div><div class="metric">Active contributions<b>${state.contributionTypes.filter(c=>c.status==='Active').length}</b></div><div class="metric">Trainings<b>${m.training}</b></div></div><h2>Contribution progress</h2><table><thead><tr><th>Contribution</th><th>Expected</th><th>Received</th><th>Outstanding</th><th>Progress</th></tr></thead><tbody>${rows}</tbody></table><h2>Skill matrix</h2><table><thead><tr><th>Skill</th>${levels.map(x=>`<th>${x}</th>`).join('')}<th>Total</th></tr></thead><tbody>${skillRows}</tbody></table></body></html>`;let win=open('','_blank');win.document.write(html);win.document.close();setTimeout(()=>win.print(),350)}function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function supabaseHeaders(token=cloudSession?.access_token){return {'apikey':SUPABASE_KEY,'Authorization':`Bearer ${token||SUPABASE_KEY}`,'Content-Type':'application/json'}}
async function authRequest(path,body){let response=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.msg||data.message||data.error_description||'Authentication failed');return data}
function storeSession(session){cloudSession=session;localStorage.setItem(SESSION_KEY,JSON.stringify(session));let email=session?.user?.email||'';document.getElementById('accountEmail').textContent=email;document.getElementById('accountButton').textContent=email?email.slice(0,2).toUpperCase():'IA'}
async function refreshCloudSession(){if(!cloudSession?.refresh_token)return false;try{let data=await authRequest('token?grant_type=refresh_token',{refresh_token:cloudSession.refresh_token});storeSession(data);return true}catch{return false}}
async function cloudFetch(path,options={}){let response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...supabaseHeaders(),...(options.headers||{})}});if(response.status===401&&await refreshCloudSession())return cloudFetch(path,options);let text=await response.text(),data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!response.ok)throw new Error(data?.message||data?.hint||(typeof data==='string'&&data)||`Supabase request failed (${response.status})`);return data}
async function pullCloud(showMessage=false){if(!cloudSession)return;try{let rows=await cloudFetch('app_modules?select=module,records,updated_at&order=module');if(!rows.length){await pushCloud(true);return}let newest=rows.reduce((max,row)=>row.updated_at>max?row.updated_at:max,'');if(newest===lastCloudUpdate)return;rows.forEach(row=>{if(CLOUD_MODULES.includes(row.module)&&Array.isArray(row.records))state[row.module]=row.records});lastCloudUpdate=newest;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));cloudReady=true;document.getElementById('lastSaved').textContent='Shared workspace synced';document.getElementById('cloudStatus').textContent=`Shared workspace synced · ${new Date().toLocaleTimeString('en-NG',{hour:'2-digit',minute:'2-digit'})}`;render();if(showMessage)toast('Shared data loaded')}catch(error){document.getElementById('lastSaved').textContent='Offline copy active';document.getElementById('cloudStatus').textContent=`Sync paused: ${error.message}`}}
async function pushCloud(initial=false){if(!cloudSession)return;clearTimeout(cloudWriteTimer);try{let rows=CLOUD_MODULES.map(module=>({module,records:state[module]||[],updated_by:cloudSession.user.id}));let result=await cloudFetch('app_modules?on_conflict=module',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify(rows)});lastCloudUpdate=(result||[]).reduce((max,row)=>row.updated_at>max?row.updated_at:max,lastCloudUpdate);cloudReady=true;document.getElementById('lastSaved').textContent='Shared workspace synced';document.getElementById('cloudStatus').textContent='All modules are synchronized';if(initial)toast('Existing browser data migrated to Supabase')}catch(error){document.getElementById('lastSaved').textContent='Saved offline · sync pending';document.getElementById('cloudStatus').textContent=`Local changes are safe. Sync error: ${error.message}`}}
function queueCloudSync(){if(!cloudSession)return;clearTimeout(cloudWriteTimer);cloudWriteTimer=setTimeout(()=>pushCloud(),700)}
async function beginCloudSession(session){storeSession(session);document.getElementById('authDialog').close();document.getElementById('lastSaved').textContent='Connecting…';await pullCloud(true);clearInterval(cloudTimer);cloudTimer=setInterval(()=>pullCloud(),15000)}
function openAuth(){let dialog=document.getElementById('authDialog');document.getElementById('authError').textContent='';if(!dialog.open)dialog.showModal()}
function setAuthMode(mode){authMode=mode;let signup=mode==='signup';document.getElementById('authTitle').textContent=signup?'Create leader account':'Sign in to continue';document.getElementById('authIntro').textContent=signup?'Create an account using your department email.':'Use your department leader account to access the shared workspace.';document.getElementById('authSubmit').textContent=signup?'Create account':'Sign in';document.getElementById('authSwitch').textContent=signup?'Already registered? Sign in':'Need an account? Create one';document.getElementById('authPassword').autocomplete=signup?'new-password':'current-password'}
async function initCloud(){let saved=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(saved?.access_token){cloudSession=saved;if(saved.expires_at&&saved.expires_at*1000<Date.now()+60000)await refreshCloudSession();if(cloudSession){await beginCloudSession(cloudSession);return}}openAuth()}
document.getElementById('authDialog').addEventListener('cancel',event=>{if(!cloudSession)event.preventDefault()});
document.getElementById('authSwitch').onclick=()=>setAuthMode(authMode==='signin'?'signup':'signin');
document.getElementById('authForm').onsubmit=async event=>{event.preventDefault();let button=document.getElementById('authSubmit'),error=document.getElementById('authError'),email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;button.disabled=true;button.textContent=authMode==='signup'?'Creating account…':'Signing in…';error.textContent='';try{if(authMode==='signup'){let data=await authRequest('signup',{email,password});if(data.access_token)await beginCloudSession(data);else{setAuthMode('signin');error.classList.add('success');error.textContent='Account created. Check your email to confirm it, then sign in.'}}else{let data=await authRequest('token?grant_type=password',{email,password});await beginCloudSession(data)}}catch(err){error.classList.remove('success');error.textContent=err.message}finally{button.disabled=false;button.textContent=authMode==='signup'?'Create account':'Sign in'}};
document.getElementById('accountButton').onclick=()=>{if(!cloudSession){openAuth();return}document.getElementById('accountDialog').showModal();updateNotificationStatus()};
document.getElementById('accountClose').onclick=()=>document.getElementById('accountDialog').close();
document.getElementById('signOutButton').onclick=async()=>{try{await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:supabaseHeaders()})}catch{}clearInterval(cloudTimer);cloudSession=null;cloudReady=false;localStorage.removeItem(SESSION_KEY);document.getElementById('accountDialog').close();document.getElementById('accountButton').textContent='IA';document.getElementById('lastSaved').textContent='Saved offline';openAuth()};
function vapidBytes(value){let padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64),bytes=Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));if(bytes.length!==65||bytes[0]!==4)throw new Error('The notification public key is invalid. Ask the administrator to update the app.');return bytes.buffer}
async function currentPushSubscription(){if(!('serviceWorker' in navigator)||!('PushManager' in window))return null;let registration=await navigator.serviceWorker.ready;return registration.pushManager.getSubscription()}
async function updateNotificationStatus(){let status=document.getElementById('notificationStatus'),button=document.getElementById('notificationButton');if(!('Notification' in window)||!('PushManager' in window)){status.textContent='Not supported by this browser';button.disabled=true;return}let subscription=await currentPushSubscription();if(subscription&&Notification.permission==='granted'){status.textContent='Enabled on this device';button.textContent='Disable';button.classList.remove('gold')}else{status.textContent=Notification.permission==='denied'?'Blocked in browser settings':'Not enabled on this device';button.textContent='Enable';button.classList.add('gold')}}
async function enableNotifications(){if(!cloudSession){toast('Sign in first');return}let button=document.getElementById('notificationButton'),isIOS=/iPhone|iPad|iPod/i.test(navigator.userAgent),standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;button.disabled=true;try{if(isIOS&&!standalone)throw new Error('On iPhone, open Illuminate from its Home Screen icon before enabling notifications.');let existing=await currentPushSubscription();if(existing){await cloudFetch(`push_subscriptions?endpoint=eq.${encodeURIComponent(existing.endpoint)}`,{method:'DELETE',headers:{'Prefer':'return=minimal'}});await existing.unsubscribe();toast('Notifications disabled on this device')}else{let permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications were not allowed. Enable them for Illuminate in iPhone Settings.');let registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidBytes(VAPID_PUBLIC_KEY)}),payload={user_id:cloudSession.user.id,endpoint:subscription.endpoint,subscription:subscription.toJSON(),device_label:navigator.userAgent.slice(0,160)};await cloudFetch('push_subscriptions?on_conflict=endpoint',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});toast('Device notifications enabled')}}catch(error){let message=error?.message||'Could not enable notifications';if(isIOS&&/string did not match|expected pattern|not supported|abort|invalid/i.test(message))message='iPhone could not create the notification subscription. Confirm iOS 16.4 or later, then remove the Home Screen app and add it again from Safari after publishing this update.';toast(message)}finally{button.disabled=false;try{await updateNotificationStatus()}catch{}}}
document.getElementById('notificationButton').onclick=enableNotifications;
document.getElementById('notificationBell').onclick=()=>{current='notifications';render()};
document.getElementById('view').addEventListener('click',event=>{let downloadButton=event.target.closest('[data-download-design]');if(downloadButton){downloadDesignFile(downloadButton.dataset.downloadDesign);return}let notification=event.target.closest('[data-notification-key]');if(notification){markNotificationRead(notification.dataset.notificationKey);current=notification.dataset.notificationPage;render();return}if(event.target.closest('#markAllNotifications'))markAllNotificationsRead()});
let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event});
window.addEventListener('appinstalled',()=>toast('Illuminate DMS installed'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
let designPreviewUrls=[];
function postRenderEnhancements(){
  if(current==='contributions')decorateContributionRows();
  if(current==='schedule')decorateMeetingTemplate();
  if(current==='designs')loadDesignThumbnails();
}
function decorateContributionRows(){
  document.querySelectorAll('#view [data-edit="contribution"]').forEach(edit=>{
    let cell=edit.closest('tr')?.cells?.[0];
    if(!cell||cell.querySelector('[data-view-contribution]'))return;
    let button=document.createElement('button');
    button.type='button';button.className='contribution-link';button.dataset.viewContribution=edit.dataset.id;
    button.title='View members who contributed';button.innerHTML=cell.innerHTML;cell.replaceChildren(button);
    button.onclick=()=>openContributionDetails(edit.dataset.id);
  });
}
function openContributionDetails(id){
  let contribution=state.contributionTypes.find(item=>item.id===id),dialog=document.getElementById('contributionDialog'),body=document.getElementById('contributionDetailBody');
  if(!contribution||!dialog||!body)return;
  let grouped={};
  state.payments.filter(payment=>payment.typeId===id).forEach(payment=>{let key=payment.memberId||'unknown';if(!grouped[key])grouped[key]={amount:0,dates:[]};grouped[key].amount+=Number(payment.amount||0);if(payment.date)grouped[key].dates.push(payment.date)});
  let contributors=Object.entries(grouped).map(([memberId,value])=>({memberId,...value})).filter(item=>item.amount>0).sort((a,b)=>memberName(a.memberId).localeCompare(memberName(b.memberId)));
  let received=contributors.reduce((sum,item)=>sum+item.amount,0),perMember=Number(contribution.amount||0);
  document.getElementById('contributionDetailTitle').textContent=contribution.name;
  document.getElementById('contributionDetailSummary').textContent=`${contributors.length} member${contributors.length===1?'':'s'} contributed · ${money(received)} received`;
  body.innerHTML=contributors.length?`<div class="table-wrap"><table class="data-table contributor-table"><thead><tr><th>Member</th><th>Amount contributed</th><th>Balance</th><th>Latest payment</th></tr></thead><tbody>${contributors.map(item=>`<tr><td><strong>${esc(memberName(item.memberId))}</strong></td><td>${money(item.amount)}</td><td>${money(Math.max(0,perMember-item.amount))}</td><td>${dateFmt(item.dates.sort().at(-1)||'')}</td></tr>`).join('')}</tbody></table></div>`:empty('No member has contributed yet');
  if(!dialog.open)dialog.showModal();
}
function decorateMeetingTemplate(){
  let template=document.querySelector('#view .editable-template[data-template="schedule"]'),wrap=template?.querySelector('.table-wrap');
  if(!wrap||template.querySelector('[data-add-agenda-row]'))return;
  let button=document.createElement('button');button.type='button';button.className='button ghost add-agenda-row';button.dataset.addAgendaRow='';button.textContent='＋ Add activity line';
  button.onclick=()=>{let body=template.querySelector('tbody'),row=document.createElement('tr'),index=body.rows.length;row.innerHTML=Array.from({length:6},(_,cell)=>`<td contenteditable="true" data-cell="${index},${cell}"></td>`).join('');body.appendChild(row);row.cells[0].focus();};
  wrap.insertAdjacentElement('afterend',button);
}
async function loadDesignThumbnails(){
  designPreviewUrls.forEach(url=>URL.revokeObjectURL(url));designPreviewUrls=[];
  let cards=[...document.querySelectorAll('#view .design-card')];
  await Promise.all(cards.map(async card=>{
    let id=card.querySelector('[data-edit="design"]')?.dataset.id,design=state.designs.find(item=>item.id===id),thumb=card.querySelector('.design-thumb');
    if(!design?.filePath||!thumb)return;
    let imageFile=(design.fileType||'').startsWith('image/')||/\.(png|jpe?g|webp|gif)$/i.test(design.fileName||'');
    if(!imageFile)return;
    try{let response=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/design-files/${storagePath(design.filePath)}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${cloudSession?.access_token||SUPABASE_KEY}`}});if(!response.ok)throw new Error('Preview unavailable');let blob=await response.blob(),url=URL.createObjectURL(blob);designPreviewUrls.push(url);let image=document.createElement('img');image.src=url;image.alt=`${design.category||'Design'} preview`;image.loading='lazy';thumb.replaceChildren(image);thumb.classList.add('has-image')}catch{thumb.title='Sign in to preview this design'}
  }));
}
let initialPage=location.hash.slice(1);if(pages.some(page=>page[0]===initialPage))current=initialPage;
render();initCloud();
