-- Illuminate Department Management System
-- Run this entire script once in Supabase: SQL Editor > New query > Run.

create table if not exists public.app_modules (
  module text primary key check (module in (
    'members', 'contributionTypes', 'payments', 'activities',
    'schedules', 'rosters', 'designs'
  )),
  records jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

alter table public.app_modules enable row level security;

drop policy if exists "Department leaders can read modules" on public.app_modules;
drop policy if exists "Department leaders can create modules" on public.app_modules;
drop policy if exists "Department leaders can update modules" on public.app_modules;

create policy "Department leaders can read modules"
on public.app_modules for select
to authenticated
using (true);

create policy "Department leaders can create modules"
on public.app_modules for insert
to authenticated
with check ((select auth.uid()) = updated_by);

create policy "Department leaders can update modules"
on public.app_modules for update
to authenticated
using (true)
with check ((select auth.uid()) = updated_by);

grant select, insert, update on public.app_modules to authenticated;
revoke all on public.app_modules from anon;

-- Keep updated_at accurate even when a client omits it.
create or replace function public.set_illuminate_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_illuminate_updated_at on public.app_modules;
create trigger set_illuminate_updated_at
before update on public.app_modules
for each row execute function public.set_illuminate_updated_at();

-- Device push subscriptions. Each signed-in leader can manage only their own devices.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  device_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Leaders read own push devices" on public.push_subscriptions;
drop policy if exists "Leaders add own push devices" on public.push_subscriptions;
drop policy if exists "Leaders update own push devices" on public.push_subscriptions;
drop policy if exists "Leaders remove own push devices" on public.push_subscriptions;

create policy "Leaders read own push devices" on public.push_subscriptions
for select to authenticated using ((select auth.uid()) = user_id);
create policy "Leaders add own push devices" on public.push_subscriptions
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Leaders update own push devices" on public.push_subscriptions
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "Leaders remove own push devices" on public.push_subscriptions
for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;
revoke all on public.push_subscriptions from anon;

-- Server-only history prevents duplicate scheduled notifications.
create table if not exists public.notification_log (
  fingerprint text primary key,
  sent_at timestamptz not null default now(),
  notification_type text not null,
  subject text not null
);

alter table public.notification_log enable row level security;
revoke all on public.notification_log from anon, authenticated;
